print "write x "
x=gets
puts "x1=#{x} #{x}"
x.chomp!
puts "x2=#{x} #{x}"
puts "x3=#{x} #{x}"
puts x.methods


puts “x.encode!#{x.encode!}”
puts “x.include?#{x.include?}”
puts “x.%#{x.%}”
puts “x.*#{x.*}”
puts “x.+#{x.+}”
puts “x.count#{x.count}”
puts “x.partition#{x.partition}”
puts “x.to_c#{x.to_c}”
puts “x.sum#{x.sum}”
puts “x.next#{x.next}”
puts “x.casecmp#{x.casecmp}”
puts “x.casecmp?#{x.casecmp?}”
puts “x.insert#{x.insert}”
puts “x.bytesize#{x.bytesize}”
puts “x.match#{x.match}”
puts “x.match?#{x.match?}”
puts “x.succ!#{x.succ!}”
puts “x.<=>#{x.<=>}”
puts “x.next!#{x.next!}”
puts “x.index#{x.index}”
puts “x.rindex#{x.rindex}”
puts “x.upto#{x.upto}”
puts “x.chr#{x.chr}”
puts “x.byteslice#{x.byteslice}”
puts “x.[]#{x.[]}”
puts “x.[]=#{x.[]=}”
puts “x.scrub!#{x.scrub!}”
puts “x.getbyte#{x.getbyte}”
puts “x.replace#{x.replace}”
puts “x.clear#{x.clear}”
puts “x.scrub#{x.scrub}”
puts “x.empty?#{x.empty?}”
puts “x.eql?#{x.eql?}”
puts “x.-@#{x.-@}”
puts “x.downcase#{x.downcase}”
puts “x.upcase#{x.upcase}”
puts “x.dump#{x.dump}”
puts “x.setbyte#{x.setbyte}”
puts “x.swapcase#{x.swapcase}”
puts “x.+@#{x.+@}”
puts “x.capitalize#{x.capitalize}”
puts “x.capitalize!#{x.capitalize!}”
puts “x.undump#{x.undump}”
puts “x.downcase!#{x.downcase!}”
puts “x.oct#{x.oct}”
puts “x.swapcase!#{x.swapcase!}”
puts “x.lines#{x.lines}”
puts “x.bytes#{x.bytes}”
puts “x.split#{x.split}”
puts “x.codepoints#{x.codepoints}”
puts “x.freeze#{x.freeze}”
puts “x.inspect#{x.inspect}”
puts “x.reverse!#{x.reverse!}”
puts “x.grapheme_clusters#{x.grapheme_clusters}”
puts “x.reverse#{x.reverse}”
puts “x.hex#{x.hex}”
puts “x.scan#{x.scan}”
puts “x.upcase!#{x.upcase!}”
puts “x.crypt#{x.crypt}”
puts “x.ord#{x.ord}”
puts “x.chars#{x.chars}”
puts “x.prepend#{x.prepend}”
puts “x.length#{x.length}”
puts “x.size#{x.size}”
puts “x.start_with?#{x.start_with?}”
puts “x.succ#{x.succ}”
puts “x.sub#{x.sub}”
puts “x.intern#{x.intern}”
puts “x.chop#{x.chop}”
puts “x.center#{x.center}”
puts “x.<<#{x.<<}”
puts “x.concat#{x.concat}”
puts “x.strip#{x.strip}”
puts “x.lstrip#{x.lstrip}”
puts “x.end_with?#{x.end_with?}”
puts “x.delete_prefix#{x.delete_prefix}”
puts “x.to_str#{x.to_str}”
puts “x.to_sym#{x.to_sym}”
puts “x.gsub!#{x.gsub!}”
puts “x.rstrip#{x.rstrip}”
puts “x.gsub#{x.gsub}”
puts “x.delete_suffix#{x.delete_suffix}”
puts “x.to_s#{x.to_s}”
puts “x.to_i#{x.to_i}”
puts “x.rjust#{x.rjust}”
puts “x.chomp!#{x.chomp!}”
puts “x.strip!#{x.strip!}”
puts “x.lstrip!#{x.lstrip!}”
puts “x.sub!#{x.sub!}”
puts “x.chomp#{x.chomp}”
puts “x.chop!#{x.chop!}”
puts “x.ljust#{x.ljust}”
puts “x.tr_s#{x.tr_s}”
puts “x.delete#{x.delete}”
puts “x.rstrip!#{x.rstrip!}”
puts “x.delete_prefix!#{x.delete_prefix!}”
puts “x.delete_suffix!#{x.delete_suffix!}”
puts “x.tr#{x.tr}”
puts “x.squeeze!#{x.squeeze!}”
puts “x.each_line#{x.each_line}”
puts “x.to_f#{x.to_f}”
puts “x.tr!#{x.tr!}”
puts “x.tr_s!#{x.tr_s!}”
puts “x.delete!#{x.delete!}”
puts “x.slice#{x.slice}”
puts “x.slice!#{x.slice!}”
puts “x.each_byte#{x.each_byte}”
puts “x.squeeze#{x.squeeze}”
puts “x.each_codepoint#{x.each_codepoint}”
puts “x.each_grapheme_cluster#{x.each_grapheme_cluster}”
puts “x.valid_encoding?#{x.valid_encoding?}”
puts “x.ascii_only?#{x.ascii_only?}”
puts “x.rpartition#{x.rpartition}”
puts “x.encoding#{x.encoding}”
puts “x.hash#{x.hash}”
puts “x.b#{x.b}”
puts “x.unicode_normalize!#{x.unicode_normalize!}”
puts “x.unicode_normalized?#{x.unicode_normalized?}”
puts “x.to_r#{x.to_r}”
puts “x.force_encoding#{x.force_encoding}”
puts “x.each_char#{x.each_char}”
puts “x.encode#{x.encode}”
puts “x.unicode_normalize#{x.unicode_normalize}”
puts “x.unpack#{x.unpack}”
puts “x.unpack1#{x.unpack1}”
puts “x.<=#{x.<=}”
puts “x.>=#{x.>=}”
puts “x.between?#{x.between?}”
puts “x.<#{x.<}”
puts “x.>#{x.>}”
puts “x.clamp#{x.clamp}”
puts “x.instance_variable_set#{x.instance_variable_set}”
puts “x.instance_variable_defined?#{x.instance_variable_defined?}”
puts “x.remove_instance_variable#{x.remove_instance_variable}”
puts “x.instance_of?#{x.instance_of?}”
puts “x.kind_of?#{x.kind_of?}”
puts “x.is_a?#{x.is_a?}”
puts “x.tap#{x.tap}”
puts “x.instance_variable_get#{x.instance_variable_get}”
puts “x.public_methods#{x.public_methods}”
puts “x.instance_variables#{x.instance_variables}”
puts “x.method#{x.method}”
puts “x.public_method#{x.public_method}”
puts “x.singleton_method#{x.singleton_method}”
puts “x.define_singleton_method#{x.define_singleton_method}”
puts “x.public_send#{x.public_send}”
puts “x.extend#{x.extend}”
puts “x.to_enum#{x.to_enum}”
puts “x.enum_for#{x.enum_for}”
puts “x.pp#{x.pp}”
puts “x.!~#{x.!~}”
puts “x.respond_to?#{x.respond_to?}”
puts “x.object_id#{x.object_id}”
puts “x.send#{x.send}”
puts “x.display#{x.display}”
puts “x.nil?#{x.nil?}”
puts “x.class#{x.class}”
puts “x.singleton_class#{x.singleton_class}”
puts “x.clone#{x.clone}”
puts “x.dup#{x.dup}”
puts “x.itself#{x.itself}”
puts “x.yield_self#{x.yield_self}”
puts “x.taint#{x.taint}”
puts “x.untaint#{x.untaint}”
puts “x.tainted?#{x.tainted?}”
puts “x.untrusted?#{x.untrusted?}”
puts “x.untrust#{x.untrust}”
puts “x.frozen?#{x.frozen?}”
puts “x.trust#{x.trust}”
puts “x.singleton_methods#{x.singleton_methods}”
puts “x.methods#{x.methods}”
puts “x.private_methods#{x.private_methods}”
puts “x.protected_methods#{x.protected_methods}”
puts “x.!#{x.!}”
puts “x.equal?#{x.equal?}”
puts “x.instance_eval#{x.instance_eval}”
puts “x.instance_exec#{x.instance_exec}”
puts “x.!=#{x.!=}”
puts “x.__id__#{x.__id__}”
puts “x.__send__#{x.__send__}”
